### ISSUE TITLE
new lint rule "identical pattern"

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/plugin-standard-lint-rules#6]
## Problem 

Some projects fill in the reference pattern for the translated pattern as a fallback. 

https://github.com/knadh/listmonk/blob/39a627d8390e88831fd808cf4e5b2aaaa1ded6f9/i18n/se.json#L22-L25

## Proposal 

Have a new lint rule that lints if the reference pattern is identical to the target pattern (aka not translated).

**Comment by samuelstroschein** [comment]
I propose the lint rule to be a warning, not an error.

**Comment by felixhaeberle** [comment]
This lint rule was introduced in aadd0ec95b4d002e95c013130ade6124a159a9ce & 08ae88203b4a61f816102bb7e5ead5cd6c66e1a0 – sorry, I overlooked that I'm not working in my fork and pushed it already to main. I wrote tests to ensure the functionality. 

@samuelstroschein Can you review?

**Comment by samuelstroschein** [comment]
@felixhaeberle see https://github.com/inlang/standard-lint-rules/commit/aadd0ec95b4d002e95c013130ade6124a159a9ce#r110370583

**Comment by felixhaeberle** [comment]
@samuelstroschein Thank you for your review, will do it asap.

**Comment by felixhaeberle** [comment]
@samuelstroschein I have further improved this by your feedback, tests still passing.
see 28894f1ff7da11d81345cfe04304a9c6a574a905

**Comment by samuelstroschein** [comment]
@felixhaeberle see https://github.com/inlang/standard-lint-rules/commit/28894f1ff7da11d81345cfe04304a9c6a574a905#r110514115

**Comment by felixhaeberle** [comment]
@samuelstroschein I think we're there! 😄
see [1236cce](https://github.com/inlang/standard-lint-rules/commit/1236ccecf5c6c16178ab38ef2820005b57e31e4b)

**Comment by samuelstroschein** [comment]
let's go publish! :)
